import {
  Connection,
  Keypair,
  PublicKey,
  Transaction,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
  sendAndConfirmTransaction,
} from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountIdempotentInstruction,
} from "@solana/spl-token";
import { randomBytes } from "crypto";
import { ESCROW_PROGRAM_ID, USDC_MINT } from "@/lib/constants";
import { getConnection, getPlatformKeypair } from "./connection";
import { usdcToLamports } from "./usdc";
// IDL is generated by `anchor build` at anchor/target/idl/marketplace_escrow.json.
// We copy it to src/lib/solana/idl.json after each build; see scripts/sync-idl.sh.
import idl from "./idl.json";

// Minimal Wallet shim. Avoids importing anchor.Wallet which webpack pulls
// from the browser bundle and breaks server route compilation.
class NodeWallet implements anchor.Wallet {
  constructor(readonly payer: Keypair) {}
  get publicKey() { return this.payer.publicKey; }
  async signTransaction<T extends anchor.web3.Transaction | anchor.web3.VersionedTransaction>(tx: T): Promise<T> {
    if ("partialSign" in tx) (tx as anchor.web3.Transaction).partialSign(this.payer);
    else (tx as anchor.web3.VersionedTransaction).sign([this.payer]);
    return tx;
  }
  async signAllTransactions<T extends anchor.web3.Transaction | anchor.web3.VersionedTransaction>(txs: T[]): Promise<T[]> {
    return Promise.all(txs.map((t) => this.signTransaction(t)));
  }
}

function getProgram(payer: Keypair): anchor.Program {
  const connection = getConnection();
  const wallet = new NodeWallet(payer);
  const provider = new anchor.AnchorProvider(connection, wallet, { commitment: "confirmed" });
  return new anchor.Program(idl as anchor.Idl, provider);
}

export function newTaskNonce(): Buffer {
  return randomBytes(32);
}
export function taskNonceFromHex(hex: string): Buffer {
  return Buffer.from(hex, "hex");
}
export function taskNonceToHex(nonce: Buffer): string {
  return nonce.toString("hex");
}

export function deriveEscrowPda(nonce: Buffer): { state: PublicKey; vault: PublicKey } {
  const [state] = PublicKey.findProgramAddressSync(
    [Buffer.from("escrow"), nonce],
    ESCROW_PROGRAM_ID,
  );
  const [vault] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), nonce],
    ESCROW_PROGRAM_ID,
  );
  return { state, vault };
}

/**
 * Fund a new escrow with USDC pulled from the agent's USDC ATA.
 * agentKeypair signs as the funder; platform is captured as the authority.
 */
export async function createEscrow(params: {
  agentKeypair: Keypair;
  bountyUsdc: number;
  taskNonce: Buffer;
}): Promise<{ signature: string; escrowPda: PublicKey; vault: PublicKey }> {
  const { agentKeypair, bountyUsdc, taskNonce } = params;
  const platform = getPlatformKeypair();
  const program = getProgram(agentKeypair);

  const { state, vault } = deriveEscrowPda(taskNonce);
  const agentAta = await getAssociatedTokenAddress(USDC_MINT, agentKeypair.publicKey, true);
  const bountyLamports = new anchor.BN(usdcToLamports(bountyUsdc).toString());

  const signature = await program.methods
    .createEscrow([...taskNonce] as any, bountyLamports)
    .accounts({
      agent: agentKeypair.publicKey,
      authority: platform.publicKey,
      escrowState: state,
      escrowTokenAccount: vault,
      agentTokenAccount: agentAta,
      mint: USDC_MINT,
      tokenProgram: TOKEN_PROGRAM_ID,
      associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      systemProgram: SystemProgram.programId,
      rent: SYSVAR_RENT_PUBKEY,
    })
    .signers([agentKeypair])
    .rpc();

  return { signature, escrowPda: state, vault };
}

export async function releaseToWorker(params: {
  taskNonce: Buffer;
  workerPubkey: PublicKey;
}): Promise<string> {
  const { taskNonce, workerPubkey } = params;
  const platform = getPlatformKeypair();
  const program = getProgram(platform);

  const { state, vault } = deriveEscrowPda(taskNonce);
  const workerAta = await getAssociatedTokenAddress(USDC_MINT, workerPubkey, true);

  // Ensure the worker has a USDC ATA before release. Idempotent: no-op if it
  // already exists. Platform pays the rent (a couple thousand lamports).
  const ataIx = createAssociatedTokenAccountIdempotentInstruction(
    platform.publicKey,
    workerAta,
    workerPubkey,
    USDC_MINT,
  );

  return program.methods
    .releaseToWorker()
    .accounts({
      authority: platform.publicKey,
      escrowState: state,
      escrowTokenAccount: vault,
      workerTokenAccount: workerAta,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .preInstructions([ataIx])
    .signers([platform])
    .rpc();
}

export async function refundToAgent(params: {
  taskNonce: Buffer;
  agentPubkey: PublicKey;
}): Promise<string> {
  const { taskNonce, agentPubkey } = params;
  const platform = getPlatformKeypair();
  const program = getProgram(platform);

  const { state, vault } = deriveEscrowPda(taskNonce);
  const agentAta = await getAssociatedTokenAddress(USDC_MINT, agentPubkey, true);
  const ataIx = createAssociatedTokenAccountIdempotentInstruction(
    platform.publicKey,
    agentAta,
    agentPubkey,
    USDC_MINT,
  );

  return program.methods
    .refundToAgent()
    .accounts({
      authority: platform.publicKey,
      escrowState: state,
      escrowTokenAccount: vault,
      agentTokenAccount: agentAta,
      tokenProgram: TOKEN_PROGRAM_ID,
    })
    .preInstructions([ataIx])
    .signers([platform])
    .rpc();
}
